# Generated by Django 4.1.7 on 2023-02-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crm_data_staging',
            options={},
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='data_received_date',
            field=models.DateField(null=True),
        ),
    ]
