# Generated by Django 4.1.7 on 2023-02-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_crm_data_staging_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_data_staging',
            name='vehicle_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
