# Generated by Django 4.0.4 on 2023-02-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_crm', '0002_rename_customer_name_crm_data_staging_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='max_date_table',
            table='Max_date_Table',
        ),
    ]
