# Generated by Django 4.0.4 on 2023-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_crm', '0003_alter_max_date_table_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_data_staging',
            name='invoice_cancle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crm_data_staging',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crm_data_staging',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='data_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
