# Generated by Django 4.1.7 on 2023-03-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_crm', '0004_crm_data_staging_invoice_cancle_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_data_staging',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='customer_delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='customer_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='driver_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='logical_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crm_data_staging',
            name='vc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
