# Generated by Django 4.1.7 on 2023-03-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_crm', '0007_alter_crm_data_dump_chassis_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionGetCRMDataToStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
