# Generated by Django 4.1.7 on 2023-03-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_crm', '0008_exceptiongetcrmdatatostaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptiongetcrmdatatostaging',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
