# Generated by Django 4.1.7 on 2023-03-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_crm', '0010_exceptiongetcrmdatatostaging_payload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exceptiongetcrmdatatostaging',
            table='EOL_EXCEPTION_GET_CRM_DATA_TO_STAGING',
        ),
    ]
